title:  "Napassorn Lerdsudwichai"
tagline: "npl"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'
  
google-ID: 'UA-109622369-1'

menu:
- {name: 'Blogs', folder: 'pages', file: 'posts.html'}
- {name: 'Projects', folder: 'pages', file: 'resources.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

social:
- {icon: 'github', link: 'https://github.com/napassornl'}
- {icon: 'linkedin-square', link: 'https://www.linkedin.com/in/napassornlerdsudwichai/'}
- {icon: 'envelope', link: 'mailto:napassorn@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
