title:  "Napassorn Lerdsudwichai"
tagline: "Hello"
description: "I was born in Thailand. I am currently a senior double majoring in Computer Engineering 
and Biomedical Engineering at Boston University. I will be graduating in May 2018."

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
- {name: 'Projects', folder: 'pages', file: 'resources.html'}
- {name: 'Posts', folder: 'pages', file: 'sample-posts.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/napassornl'}
- {icon: 'linkedin-square', link: 'https://www.linkedin.com/in/napassornlerdsudwichai/'}
- {icon: 'instagram', link: 'https://instagram.com/napassor.n'}
- {icon: 'facebook', link: 'https://www.facebook.com/napassorn1995'}
- {icon: 'twitter', link: 'https://twitter.com/napassornlerds'}
- {icon: 'envelope', link: 'mailto:napalerd@bu.edu'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
